namespace MVCCrudOrnek.Models
{
    public static class Veri
    {
        public static List<Ogrenci> Ogrenciler { get; set; } = new()
        {
            new Ogrenci { Id = 1, Ad = "Begüm", DogumYili = 1999, TakimId = 36 },
            new Ogrenci { Id = 2, Ad = "Berkan", DogumYili = 2000, TakimId = 36 },
            new Ogrenci { Id = 3, Ad = "Mehmet Ali", DogumYili = 1996, TakimId = 36 },
            new Ogrenci { Id = 4, Ad = "Murat", DogumYili = 2004, TakimId = 34 },
            new Ogrenci { Id = 5, Ad = "Serhat", DogumYili = 2003, TakimId = 34 },
            new Ogrenci { Id = 6, Ad = "Mahir", DogumYili = 1998, TakimId = 20 },
            new Ogrenci { Id = 7, Ad = "Yaşar", DogumYili = 2001, TakimId = 40 },
            new Ogrenci { Id = 8, Ad = "Melis", DogumYili = 2001, TakimId = 15 }
        };

        public static List<Takim> Takimlar { get; set; } = new()
        {
            new Takim() { Id = 1, TakimAd = "1461 Trabzon" },
            new Takim() { Id = 2, TakimAd = "24 Erzincanspor" },
            new Takim() { Id = 3, TakimAd = "68 Aksarayspor" },
            new Takim() { Id = 4, TakimAd = "Adana 01" },
            new Takim() { Id = 5, TakimAd = "Adana Demirspor" },
            new Takim() { Id = 6, TakimAd = "Adanaspor" },
            new Takim() { Id = 7, TakimAd = "Afyonspor" },
            new Takim() { Id = 8, TakimAd = "Alanyaspor" },
            new Takim() { Id = 9, TakimAd = "Altay" },
            new Takim() { Id = 10, TakimAd = "Altınordu" },
            new Takim() { Id = 11, TakimAd = "Amed" },
            new Takim() { Id = 12, TakimAd = "Ankara Demirspor" },
            new Takim() { Id = 13, TakimAd = "Ankara Keçiörengücü" },
            new Takim() { Id = 14, TakimAd = "Ankaraspor" },
            new Takim() { Id = 15, TakimAd = "Antalyaspor" },
            new Takim() { Id = 16, TakimAd = "Arnavutköy Belediyespor" },
            new Takim() { Id = 17, TakimAd = "Bandırmaspor" },
            new Takim() { Id = 18, TakimAd = "Batman Petrolspor" },
            new Takim() { Id = 19, TakimAd = "Belediye Derincespor" },
            new Takim() { Id = 20, TakimAd = "Beşiktaş" },
            new Takim() { Id = 21, TakimAd = "Beyoğlu Yeni Çarşı" },
            new Takim() { Id = 22, TakimAd = "Bodrum" },
            new Takim() { Id = 23, TakimAd = "Boluspor" },
            new Takim() { Id = 24, TakimAd = "Bucaspor 1928" },
            new Takim() { Id = 25, TakimAd = "Çaykur Rizespor" },
            new Takim() { Id = 26, TakimAd = "Çorum" },
            new Takim() { Id = 27, TakimAd = "Diyarbekirspor" },
            new Takim() { Id = 28, TakimAd = "Elazığspor" },
            new Takim() { Id = 29, TakimAd = "Erbaaspor" },
            new Takim() { Id = 30, TakimAd = "Erzurumspor" },
            new Takim() { Id = 31, TakimAd = "Esenler Erokspor" },
            new Takim() { Id = 32, TakimAd = "Eyüpspor" },
            new Takim() { Id = 33, TakimAd = "Fatih Karagümrük" },
            new Takim() { Id = 34, TakimAd = "Fenerbahçe" },
            new Takim() { Id = 35, TakimAd = "Fethiyespor" },
            new Takim() { Id = 36, TakimAd = "Galatasaray" },
            new Takim() { Id = 37, TakimAd = "Gaziantep" },
            new Takim() { Id = 38, TakimAd = "Gençlerbirliği" },
            new Takim() { Id = 39, TakimAd = "Giresunspor" },
            new Takim() { Id = 40, TakimAd = "Göztepe" },
            new Takim() { Id = 41, TakimAd = "Hatayspor" },
            new Takim() { Id = 42, TakimAd = "Iğdır" },
            new Takim() { Id = 43, TakimAd = "İnegölspor" },
            new Takim() { Id = 44, TakimAd = "İskenderunspor" },
            new Takim() { Id = 45, TakimAd = "Isparta 32" },
            new Takim() { Id = 46, TakimAd = "İstanbul Başakşehir" },
            new Takim() { Id = 47, TakimAd = "İstanbulspor" },
            new Takim() { Id = 48, TakimAd = "Karacabey Belediyespor" },
            new Takim() { Id = 49, TakimAd = "Karaköprü Belediyespor" },
            new Takim() { Id = 50, TakimAd = "Karaman" },
            new Takim() { Id = 51, TakimAd = "Kasımpaşa" },
            new Takim() { Id = 52, TakimAd = "Kastamonuspor 1966" },
            new Takim() { Id = 53, TakimAd = "Kayserispor" },
            new Takim() { Id = 54, TakimAd = "Kepezspor" },
            new Takim() { Id = 55, TakimAd = "Kırklarelispor" },
            new Takim() { Id = 56, TakimAd = "Kocaelispor" },
            new Takim() { Id = 57, TakimAd = "Konyaspor" },
            new Takim() { Id = 58, TakimAd = "Manisa" },
            new Takim() { Id = 59, TakimAd = "Menemen" },
            new Takim() { Id = 60, TakimAd = "MKE Ankaragücü" },
            new Takim() { Id = 61, TakimAd = "Nazilli Belediyespor" },
            new Takim() { Id = 62, TakimAd = "Pendikspor" },
            new Takim() { Id = 63, TakimAd = "Sakaryaspor" },
            new Takim() { Id = 64, TakimAd = "Samsunspor" },
            new Takim() { Id = 65, TakimAd = "Şanlıurfaspor" },
            new Takim() { Id = 66, TakimAd = "Sarıyer" },
            new Takim() { Id = 67, TakimAd = "Serik Belediyespor" },
            new Takim() { Id = 68, TakimAd = "Sivasspor" },
            new Takim() { Id = 69, TakimAd = "Somaspor" },
            new Takim() { Id = 70, TakimAd = "Trabzonspor" },
            new Takim() { Id = 71, TakimAd = "Tuzlaspor" },
            new Takim() { Id = 72, TakimAd = "Ümraniyespor" },
            new Takim() { Id = 73, TakimAd = "Vanspor" },
            new Takim() { Id = 74, TakimAd = "Yeni Malatyaspor" },
            new Takim() { Id = 75, TakimAd = "Yeni Mersin İdmanyurdu" }
        };
    }
}
